version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: password123
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
  app:
    image: my-node-app
    port:
      - 1337:3000
